apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: neuron-cluster
  region: us-east-1
  version: "1.30"

addons:
- name: vpc-cni
  version: latest

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    
iam:
  withOIDC: true
